"""add user_id and post_id to comments table

Revision ID: 553869fb76cf
Revises: 70253cfaeeb0
Create Date: 2023-11-16 08:48:29.191224

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '553869fb76cf'
down_revision = '70253cfaeeb0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('comments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('post_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'posts', ['post_id'], ['id'])
        batch_op.create_foreign_key(None, 'users', ['user_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('comments', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('post_id')
        batch_op.drop_column('user_id')

    # ### end Alembic commands ###
